### ISSUE TITLE
unable to build kubernetes objects from release manifest

### ISSUE THREAD

**Issue by funyx** [okteto/cert-manager-webhook-civo#8]
after
```
helm repo add jetstack https://charts.jetstack.io
helm repo add okteto https://charts.okteto.com
helm repo update
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.7.1 --set installCRDs=true
```
i run
```
helm install --namespace cert-manager cert-manager-webhook-civo okteto/cert-manager-webhook-civo
```
and i get
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1"
```

cleanup
```
helm --namespace cert-manager delete cert-manager
kubectl delete namespace cert-manager
helm uninstall --namespace cert-manager cert-manager-webhook-civo
```

**Comment by rberrelleza** [comment]
What version of kubernetes where you trying to install this on?

**Comment by funyx** [comment]
not quite sure, but i would guess it was the recommended one

**Comment by venkatesh2090** [comment]
Hi, I'm having the same issue. Here's the versions of my client and server @rberrelleza.
```sh
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s1", GitCommit:"10bca343e85180f668522fe252552da20220cb7a", GitTreeState:"clean", BuildDate:"2021-09-23T22:46:18Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by venkatesh2090** [comment]
I think I found the issue. The `admissionregistration.k8s.io/v1beta1` apiVersion was removed as of k8s `v1.22` as mentioned [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22). The chart should be using `admissionregistration.k8s.io/v1` instead in `apiservice.yaml`.

**Comment by venkatesh2090** [comment]
Looks like it's already using it my bad. But when I did helm template I get
```yaml
# Source: cert-manager-webhook-civo/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.civo.webhook.okteto.com
  labels:
    helm.sh/chart: cert-manager-webhook-civo-0.2.0
    app.kubernetes.io/name: cert-manager-webhook-civo
    app.kubernetes.io/instance: cert-manager-webhook-civo
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:  
     cert-manager.io/inject-ca-from: "default/cert-manager-webhook-civo-webhook-tls"
spec:
  group: civo.webhook.okteto.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-civo
    namespace: default
  version: v1alpha1
```
Maybe the helm repo needs to be updated? I used the chart from git instead which worked.
